### PR TITLE
Extract BCTest

### LINKED ISSUE #2387: Spuriously failing tests
- `byzcoin.TestSecureDarc`
- `byzcoin.TestDeferred_WrongSignature`

### PR DESCRIPTION
**Pull request by ineiti**
This PR makes a nicer BCTest structure that can be used in the different tests.
Its main purpose was to have a correct 'CloseAll' method that waits for all
activity to stop.
But finally it also cleans up a lot of trailing cruft in different tests.

The goal is to have a BCTest structure that can also be used by other modules.
For this reason BCTest is exported in the main package.
For any idea how to make this cleaner, comments are welcome :)

Ran the tests from #2387 in a loop here:
https://travis-ci.com/github/dedis/cothority/jobs/394084093
https://travis-ci.com/github/dedis/cothority/builds/187765748

Closes #2387

### CODE REVIEW

File: byzcoin/service_test.go [hunk 1]
```diff
@@ -1870,23 +1843,20 @@ func TestService_CheckValidPeers(t *testing.T) {
...
 		// Add dummy transaction to ensure new node is updated
-		counter = addDummyTxs(t, s, 1, 1, counter)
-
-		// Wait until all servers have included the block
-		require.NoError(t, cl.WaitPropagation(-1))
+		addDummyTxs(b, 1, 1)
 
 		// Check valid peers in all current servers
-		for _, srv := range allServers[index : index+5] {
+		for _, srv := range allServers[index : index+4] {
```
Comment (tharvik) [inline byzcoin/service_test.go:1859]: Kinda magic, can you add a `const` or a `len` about it?

**Review by tharvik — APPROVED** [review]

**Comment by ineiti** [comment]
Forgot to mention that the 'entry-point' for the code-review is `bcadmin/bctest.go` - that's the most important file. All the rest is mostly using the new BCTest structure...
