### PR TITLE
Fix issue with isSecureContext with local content

### LINKED ISSUE #2104: network.Roster.fromTOML doesn't take Url field into account
I found out that the `network.Roster.fromTOML` function always tries to connect to secure web socket, even if the `Url` field is not set or set to `http://...`.

**How to reproduce**

1) Launch some conodes locally (`./run_nodes.sh`)
2) Set up and use `external/js/cothority/index.html` (run `npm run bundle` before)
3) Try to load the generated `public.toml` file from the step 1, which won't work.

### PR DESCRIPTION
**Pull request by Gilthoniel**
This changes the logic to instead check the current protocol so that
browser context with a location using HTTPS will always use WSS.

Fixes #2104

---

🙅‍ Friendly checklist:

- [x] 0. Code comments are added (or updated) when/where needed and explain the WHY of the code.
- [x] 1. Design choices, user documentation and any additional doc are added (or updated) in READMEs.
- [x] 2. Any new behaviour is tested and small units of code that can be are unit tested.
- [x] 3. Code comments are added on tests to explain what they do.
- [x] 4. Errors are systematically wrapped with a meaningful message using `xerrors.Errorf` and the `%v` verb.
- [x] 5. Hard limit of 80 chars is always respected.
- [x] 6. Changes are backward compatible.
- [x] 7. Indentation level does not exceed 5, although 4 is already suspicious.
- [x] 8. Functions, files, and packages are kept to a manageable size and decomposed into smaller units if needed.
- [x] 9. There are no magic values.

### CODE REVIEW

File: external/js/cothority/src/network/connection.ts [hunk 1]
```diff
@@ -61,8 +61,10 @@ export class WebSocketConnection {
      */
     constructor(addr: string, service: string) {
         const url = new URL(addr, {});
-        if (typeof window !== "undefined" && window.isSecureContext === true) {
-            url.set("protocol", "wss");
+        if (typeof globalThis !== "undefined" && typeof globalThis.location !== "undefined") {
```
Comment (tharvik) [inline external/js/cothority/src/network/connection.ts]: when not running the tests, `globalThis` isn't defined, so, never going to `wss`, even on secure pages?

Comment (Gilthoniel) [reply external/js/cothority/src/network/connection.ts]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis

Comment (tharvik) [reply external/js/cothority/src/network/connection.ts]: I learn everyday with MDN.

File: external/js/cothority/spec/helpers/global-this.ts [hunk 2]
```diff
@@ -0,0 +1,5 @@
+
+beforeAll(() => {
+    // @ts-ignore
+    global.globalThis = global;
```
Comment (nkcr) [inline external/js/cothority/spec/helpers/global-this.ts]: Thanks for the fix! In addition I would just explain why this is needed and how it is used.
