### PR TITLE
cosi doesn't hang anymore 839

### LINKED ISSUE #839: cosi-service roster-error
Now: when cosi-service receives a signature request with a roster where he is not the root, it will fail.

Wanted: also sign with a roster if we're not the first node.

ToDo: 
- write test with failing behaviour if we're not the first node
- use `GenerateNaryTreeWithRoot` instead of `GenerateBinaryTree` in `cosi/service/cosi.go:52`

### PR DESCRIPTION
**Pull request by christophebertrand**
closes #839

### CODE REVIEW

File: cosi/service/cosi_test.go [hunk 1]
```diff
@@ -34,6 +34,33 @@ func TestServiceCosi(t *testing.T) {
...
+	defer local.CloseAll()
+
+	// Send a request to the service to the second host
+	client := NewTestClient(local)
+	msg := []byte("hello cosi service")
+	serviceReq := &SignatureRequest{
+		Roster:  el,
+		Message: msg,
+	}
+	dst := el.List[1]
```
Comment (ineiti) [inline cosi/service/cosi_test.go]: Can you do a `for _, dst := range el.List` and then test for all hosts? I think this would be the best test we can do for that part.

**Comment by ineiti** [comment]
Don't worry about `jvss/simulation` failing - it will go away.
