### PR TITLE
Fix some network issues

### LINKED ISSUE #674: Data race in propagate protcol
<details><summary>Race in propagate protocol (expand for details)</summary>
<pre><code>
==================
WARNING: DATA RACE
Read at 0x00c4200d4908 by goroutine 90:
  github.com/dedis/cothority/protocols/manage.TestPropagate.func1()
      /home/travis/gopath/src/github.com/dedis/cothority/protocols/manage/propagate_test.go:38 +0x124
  github.com/dedis/cothority/protocols/manage.(*Propagate).Dispatch()
      github.com/dedis/cothority/protocols/manage/_test/_obj_test/propagate.go:165 +0xea3
Previous write at 0x00c4200d4908 by goroutine 86:
  github.com/dedis/cothority/protocols/manage.TestPropagate.func1()
      /home/travis/gopath/src/github.com/dedis/cothority/protocols/manage/propagate_test.go:38 +0x13d
  github.com/dedis/cothority/protocols/manage.(*Propagate).Dispatch()
      github.com/dedis/cothority/protocols/manage/_test/_obj_test/propagate.go:165 +0xea3
Goroutine 90 (running) created at:
  github.com/dedis/cothority/sda.(*Overlay).TransmitMsg()
      /home/travis/gopath/src/github.com/dedis/cothority/sda/overlay.go:201 +0xd0d
  github.com/dedis/cothority/sda.(*Overlay).checkPendingMessages.func1()
      /home/travis/gopath/src/github.com/dedis/cothority/sda/overlay.go:274 +0x2ba
Goroutine 86 (running) created at:
  github.com/dedis/cothority/sda.(*Overlay).TransmitMsg()
      /home/travis/gopath/src/github.com/dedis/cothority/sda/overlay.go:201 +0xd0d
  github.com/dedis/cothority/sda.(*Overlay).checkPendingMessages.func1()
      /home/travis/gopath/src/github.com/dedis/cothority/sda/overlay.go:274 +0x2ba
</code></pre>
</details>

See: https://travis-ci.org/dedis/cothority/builds/174246374#L198-L223 (build might have been restarted though)

### PR DESCRIPTION
**Pull request by nikkolasg**
resolves #674 
Fixing some networks issues like #671 and #674 and #669  and merge #663 + #662 
Let's see what travis does.

### CODE REVIEW

**Comment by nikkolasg** [comment]
for the moment 3 travis run are OK.

**Comment by nikkolasg** [comment]
resolves #674

**Comment by nikkolasg** [comment]
resolves #671

File: network/local.go [hunk 1]
```diff
@@ -277,27 +275,28 @@ func (lc *LocalConn) Type() ConnType {
...
 // The messages are marshalled and stored in the queue as a slice of bytes.
 type connQueue struct {
-	*sync.Cond
-	queue  [][]byte
-	closed bool
+	queue  chan []byte
+	closed chan bool
 }
 
+// LocalMaxBuffer is the size of packets that can be sent simultaneously to the
```
Comment (Liamsi) [inline network/local.go]: the number of packets

File: network/local.go [hunk 2]
```diff
@@ -306,36 +305,37 @@ func (c *connQueue) push(buff []byte) {
...
-	defer c.L.Unlock()
-	c.closed = true
-	c.Broadcast()
+func (c *connQueue) close() error {
+	select {
+	case _, opened := <-c.closed:
+		if !opened {
+			return ErrClosed
+		}
+		close(c.closed)
```
Comment (ineiti) [inline network/local.go]: put the `close` outside of the case

File: coveralls.sh [hunk 3]
```diff
@@ -27,7 +27,12 @@ all_tests_passed=true
 echo "mode: atomic" > profile.cov
 for dir in ${DIR_SOURCE};
 do
-    go test -short -race -covermode=atomic -coverprofile=$dir/profile.tmp $dir
+    if [[ $dir =~ "./services/" ]]; then
+        go test -v -short -race -covermode=atomic -coverprofile=$dir/profile.tmp $dir
+    else
+        go test -short -race -covermode=atomic -coverprofile=$dir/profile.tmp $dir
+    fi
```
Comment (nikkolasg) [inline coveralls.sh]: it was to try to debug the services data race / timeout stuff but here it does not matter I removed it

File: network/local.go [hunk 4]
```diff
@@ -306,36 +303,37 @@ func (c *connQueue) push(buff []byte) {
...
+	return nil
 }
 
 // isClosed returns whether this queue is closed or not.
 func (c *connQueue) isClosed() bool {
-	c.L.Lock()
-	defer c.L.Unlock()
-	return c.closed
+	select {
+	case _, opened := <-c.queue:
```
Comment (ineiti) [inline network/local.go]: What happens if a message is pending and `isClosed` is called? Won't the message be discarded?

File: network/local.go [hunk 5]
```diff
@@ -306,36 +303,37 @@ func (c *connQueue) push(buff []byte) {
...
-	c.L.Lock()
-	defer c.L.Unlock()
-	c.closed = true
-	c.Broadcast()
+func (c *connQueue) close() error {
+	select {
+	case _, opened := <-c.queue:
+		if !opened {
+			return ErrClosed
+		}
```
Comment (ineiti) [inline network/local.go]: Still needs to close the `c.queue`

**Comment by Liamsi** [comment]
The last commit didn't make things better:

<details><summary>See build https://github.com/dedis/cothority/pull/673/commits/40509cc833ded5bc3f33adbf2f83891eba47aac3 </summary>
<pre><code>
receive server identity failed: Received wrong type during negotiation network.SimpleMessage
--- FAIL: TestClientLocal (0.02s)
	Error Trace:	client_test.go:36
			client_test.go:16
	Error:		Expected nil, but got: &errors.errorString{s:"Connection Closed"}
		
--- FAIL: TestLocalRouter (0.00s)
	local_test.go:22: Should not have returned something
receive server identity failed: Received wrong type during negotiation network.SimpleMessage
Didn't finish in time
goroutine profile: total 6
2 @ 0x431e7d 0x431f6e 0x406877 0x406655 0x49a611 0x4c3293 0x49b72f 0x465461
#	0x49a610	github.com/dedis/cothority/network.(*LocalListener).Listen+0x2d0	github.com/dedis/cothority/network/_test/_obj_test/local.go:465
#	0x4c3292	github.com/dedis/cothority/network.(*LocalHost).Listen+0x72		<autogenerated>:65
#	0x49b72e	github.com/dedis/cothority/network.(*Router).Start+0xfe			github.com/dedis/cothority/network/_test/_obj_test/router.go:93
1 @ 0x431e7d 0x431f6e 0x406877 0x406655 0x48acbe 0x48f5aa 0x48a6da 0x48c09b 0x48b270 0x600209 0x465461
#	0x48acbd	testing.(*T).Run+0x56d					/home/travis/.gimme/versions/go1.7.linux.amd64/src/testing/testing.go:647
#	0x48f5a9	testing.RunTests.func1+0xb9				/home/travis/.gimme/versions/go1.7.linux.amd64/src/testing/testing.go:793
#	0x48a6d9	testing.tRunner+0xc9					/home/travis/.gimme/versions/go1.7.linux.amd64/src/testing/testing.go:610
#	0x48c09a	testing.RunTests+0x4ba					/home/travis/.gimme/versions/go1.7.linux.amd64/src/testing/testing.go:799
#	0x48b26f	testing.(*M).Run+0x12f					/home/travis/.gimme/versions/go1.7.linux.amd64/src/testing/testing.go:743
#	0x600208	github.com/dedis/cothority/log.MainTest.func1+0x38	/home/travis/gopath/src/github.com/dedis/cothority/log/lvl.go:386
1 @ 0x431e7d 0x431f6e 0x406877 0x406655 0x4ae4cf 0x4adda5 0x48a6da 0x465461
#	0x4ae4ce	github.com/dedis/cothority/network.testRouterAutoConnection+0x70e	/home/travis/gopath/src/github.com/dedis/cothority/network/router_test.go:110
#	0x4adda4	github.com/dedis/cothority/network.TestRouterAutoConnectionLocal+0x44	/home/travis/gopath/src/github.com/dedis/cothority/network/router_test.go:71
#	0x48a6d9	testing.tRunner+0xc9							/home/travis/.gimme/versions/go1.7.linux.amd64/src/testing/testing.go:610
1 @ 0x465461
1 @ 0x55b5ee 0x55b38a 0x556c0e 0x5fe8a3 0x4ad694 0x401fa7 0x431a6d 0x465461
#	0x55b5ed	runtime/pprof.writeRuntimeProfile+0xbd			/home/travis/.gimme/versions/go1.7.linux.amd64/src/runtime/pprof/pprof.go:614
#	0x55b389	runtime/pprof.writeGoroutine+0xc9			/home/travis/.gimme/versions/go1.7.linux.amd64/src/runtime/pprof/pprof.go:576
#	0x556c0d	runtime/pprof.(*Profile).WriteTo+0x47d			/home/travis/.gimme/versions/go1.7.linux.amd64/src/runtime/pprof/pprof.go:298
#	0x5fe8a2	github.com/dedis/cothority/log.MainTest+0x312		/home/travis/gopath/src/github.com/dedis/cothority/log/lvl.go:395
#	0x4ad693	github.com/dedis/cothority/network.TestMain+0x53	/home/travis/gopath/src/github.com/dedis/cothority/network/network_test.go:10
#	0x401fa6	main.main+0x316						github.com/dedis/cothority/network/_test/_testmain.go:188
#	0x431a6c	runtime.main+0x18c					/home/travis/.gimme/versions/go1.7.linux.amd64/src/runtime/proc.go:183
FAIL	github.com/dedis/cothority/network	180.014s
?   	github.com/dedis/cothority/protocols	[no test files]
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
==================
WARNING: DATA RACE
Write at 0x00c4200de900 by goroutine 8:
  runtime.closechan()
      /home/travis/.gimme/versions/go1.7.linux.amd64/src/runtime/chan.go:303 +0x0
  github.com/dedis/cothority/protocols/bftcosi.(*ProtocolBFTCoSi).Shutdown()
      github.com/dedis/cothority/protocols/bftcosi/_test/_obj_test/bftcosi.go:273 +0xc8
  github.com/dedis/cothority/sda.(*TreeNodeInstance).Close()
      /home/travis/gopath/src/github.com/dedis/cothority/sda/treenode.go:269 +0x240
  github.com/dedis/cothority/sda.(*Overlay).nodeDelete()
      /home/travis/gopath/src/github.com/dedis/cothority/sda/overlay.go:415 +0x279
  github.com/dedis/cothority/sda.(*Overlay).Close()
      /home/travis/gopath/src/github.com/dedis/cothority/sda/overlay.go:434 +0x43c
  github.com/dedis/cothority/sda.(*Conode).Close()
      /home/travis/gopath/src/github.com/dedis/cothority/sda/conode.go:79 +0x69
  github.com/dedis/cothority/sda.(*LocalTest).CloseAll()
      /home/travis/gopath/src/github.com/dedis/cothority/sda/local.go:157 +0x2b8
  github.com/dedis/cothority/protocols/bftcosi.runProtocolOnceGo()
      /home/travis/gopath/src/github.com/dedis/cothority/protocols/bftcosi/bftcosi_test.go:246 +0x1a05
  github.com/dedis/cothority/protocols/bftcosi.runProtocolOnce()
      /home/travis/gopath/src/github.com/dedis/cothority/protocols/bftcosi/bftcosi_test.go:186 +0x74
  github.com/dedis/cothority/protocols/bftcosi.runProtocol()
      /home/travis/gopath/src/github.com/dedis/cothority/protocols/bftcosi/bftcosi_test.go:181 +0xc1
  github.com/dedis/cothority/protocols/bftcosi.TestBftCoSi()
      /home/travis/gopath/src/github.com/dedis/cothority/protocols/bftcosi/bftcosi_test.go:64 +0x122
  testing.tRunner()
      /home/travis/.gimme/versions/go1.7.linux.amd64/src/testing/testing.go:610 +0xc9
Previous read at 0x00c4200de900 by goroutine 17:
  runtime.chansend()
      /home/travis/.gimme/versions/go1.7.linux.amd64/src/runtime/chan.go:122 +0x0
  github.com/dedis/cothority/protocols/bftcosi.(*ProtocolBFTCoSi).startAnnouncement()
      github.com/dedis/cothority/protocols/bftcosi/_test/_obj_test/bftcosi.go:486 +0xa8
  github.com/dedis/cothority/protocols/bftcosi.(*ProtocolBFTCoSi).Start.func1()
      github.com/dedis/cothority/protocols/bftcosi/_test/_obj_test/bftcosi.go:156 +0x58
Goroutine 8 (running) created at:
  testing.(*T).Run()
      /home/travis/.gimme/versions/go1.7.linux.amd64/src/testing/testing.go:646 +0x52f
  testing.RunTests.func1()
      /home/travis/.gimme/versions/go1.7.linux.amd64/src/testing/testing.go:793 +0xb9
  testing.tRunner()
      /home/travis/.gimme/versions/go1.7.linux.amd64/src/testing/testing.go:610 +0xc9
  testing.RunTests()
      /home/travis/.gimme/versions/go1.7.linux.amd64/src/testing/testing.go:799 +0x4ba
  testing.(*M).Run()
      /home/travis/.gimme/versions/go1.7.linux.amd64/src/testing/testing.go:743 +0x12f
  github.com/dedis/cothority/log.MainTest.func1()
      /home/travis/gopath/src/github.com/dedis/cothority/log/lvl.go:386 +0x38
Goroutine 17 (finished) created at:
  github.com/dedis/cothority/protocols/bftcosi.(*ProtocolBFTCoSi).Start()
      github.com/dedis/cothority/protocols/bftcosi/_test/_obj_test/bftcosi.go:157 +0xea
==================
--- FAIL: TestBftCoSi (60.04s)
	bftcosi_test.go:187: Waited 1m0s for BFTCoSi to finish ...
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
==================
WARNING: DATA RACE
Write at 0x00c42013d920 by goroutine 70:
  runtime.closechan()
      /home/travis/.gimme/versions/go1.7.linux.amd64/src/runtime/chan.go:303 +0x0
  github.com/dedis/cothority/protocols/bftcosi.(*ProtocolBFTCoSi).Shutdown()
      github.com/dedis/cothority/protocols/bftcosi/_test/_obj_test/bftcosi.go:273 +0xc8
  github.com/dedis/cothority/sda.(*TreeNodeInstance).Close()
      /home/travis/gopath/src/github.com/dedis/cothority/sda/treenode.go:269 +0x240
  github.com/dedis/cothority/sda.(*Overlay).nodeDelete()
      /home/travis/gopath/src/github.com/dedis/cothority/sda/overlay.go:415 +0x279
  github.com/dedis/cothority/sda.(*Overlay).Close()
      /home/travis/gopath/src/github.com/dedis/cothority/sda/overlay.go:434 +0x43c
  github.com/dedis/cothority/sda.(*Conode).Close()
      /home/travis/gopath/src/github.com/dedis/cothority/sda/conode.go:79 +0x69
  github.com/dedis/cothority/sda.(*LocalTest).CloseAll()
      /home/travis/gopath/src/github.com/dedis/cothority/sda/local.go:157 +0x2b8
  github.com/dedis/cothority/protocols/bftcosi.runProtocolOnceGo()
      /home/travis/gopath/src/github.com/dedis/cothority/protocols/bftcosi/bftcosi_test.go:246 +0x1a05
  github.com/dedis/cothority/protocols/bftcosi.runProtocolOnce()
      /home/travis/gopath/src/github.com/dedis/cothority/protocols/bftcosi/bftcosi_test.go:186 +0x74
  github.com/dedis/cothority/protocols/bftcosi.runProtocol()
      /home/travis/gopath/src/github.com/dedis/cothority/protocols/bftcosi/bftcosi_test.go:181 +0xc1
  github.com/dedis/cothority/protocols/bftcosi.TestCheckRefuse()
      /home/travis/gopath/src/github.com/dedis/cothority/protocols/bftcosi/bftcosi_test.go:110 +0x1d0
  testing.tRunner()
      /home/travis/.gimme/versions/go1.7.linux.amd64/src/testing/testing.go:610 +0xc9
Previous read at 0x00c42013d920 by goroutine 79:
  runtime.chansend()
      /home/travis/.gimme/versions/go1.7.linux.amd64/src/runtime/chan.go:122 +0x0
  github.com/dedis/cothority/protocols/bftcosi.(*ProtocolBFTCoSi).startAnnouncement()
      github.com/dedis/cothority/protocols/bftcosi/_test/_obj_test/bftcosi.go:486 +0xa8
  github.com/dedis/cothority/protocols/bftcosi.(*ProtocolBFTCoSi).Start.func1()
      github.com/dedis/cothority/protocols/bftcosi/_test/_obj_test/bftcosi.go:156 +0x58
Goroutine 70 (running) created at:
  testing.(*T).Run()
      /home/travis/.gimme/versions/go1.7.linux.amd64/src/testing/testing.go:646 +0x52f
  testing.RunTests.func1()
      /home/travis/.gimme/versions/go1.7.linux.amd64/src/testing/testing.go:793 +0xb9
  testing.tRunner()
      /home/travis/.gimme/versions/go1.7.linux.amd64/src/testing/testing.go:610 +0xc9
  testing.RunTests()
      /home/travis/.gimme/versions/go1.7.linux.amd64/src/testing/testing.go:799 +0x4ba
  testing.(*M).Run()
      /home/travis/.gimme/versions/go1.7.linux.amd64/src/testing/testing.go:743 +0x12f
  github.com/dedis/cothority/log.MainTest.func1()
      /home/travis/gopath/src/github.com/dedis/cothority/log/lvl.go:386 +0x38
Goroutine 79 (finished) created at:
  github.com/dedis/cothority/protocols/bftcosi.(*ProtocolBFTCoSi).Start()
      github.com/dedis/cothority/protocols/bftcosi/_test/_obj_test/bftcosi.go:157 +0xea
==================
--- FAIL: TestCheckRefuse (60.02s)
	bftcosi_test.go:187: Waited 1m0s for BFTCoSi to finish ...
receive server identity failed: receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
Received wrong type during negotiation sda.ProtocolMsg
Didn't finish in time
goroutine profile: total 9
3 @ 0x431afd 0x431bee 0x4064f7 0x4062d5 0x5d3f29 0x5e1033 0x5d4da7 0x4650e1
#	0x5d3f28	github.com/dedis/cothority/network.(*LocalListener).Listen+0x288	/home/travis/gopath/src/github.com/dedis/cothority/network/local.go:397
#	0x5e1032	github.com/dedis/cothority/network.(*LocalHost).Listen+0x72		<autogenerated>:65
#	0x5d4da6	github.com/dedis/cothority/network.(*Router).Start+0xe6			/home/travis/gopath/src/github.com/dedis/cothority/network/router.go:83
1 @ 0x431afd 0x431bee 0x4064f7 0x4062d5 0x48a93e 0x48f22a 0x48a35a 0x48bd1b 0x48aef0 0x54d679 0x4650e1
#	0x48a93d	testing.(*T).Run+0x56d					/home/travis/.gimme/versions/go1.7.linux.amd64/src/testing/testing.go:647
#	0x48f229	testing.RunTests.func1+0xb9				/home/travis/.gimme/versions/go1.7.linux.amd64/src/testing/testing.go:793
#	0x48a359	testing.tRunner+0xc9					/home/travis/.gimme/versions/go1.7.linux.amd64/src/testing/testing.go:610
#	0x48bd1a	testing.RunTests+0x4ba					/home/travis/.gimme/versions/go1.7.linux.amd64/src/testing/testing.go:799
#	0x48aeef	testing.(*M).Run+0x12f					/home/travis/.gimme/versions/go1.7.linux.amd64/src/testing/testing.go:743
#	0x54d678	github.com/dedis/cothority/log.MainTest.func1+0x38	/home/travis/gopath/src/github.com/dedis/cothority/log/lvl.go:386
1 @ 0x431afd 0x431bee 0x4064f7 0x4062d5 0x492d1a 0x4650e1
#	0x492d19	github.com/dedis/cothority/protocols/bftcosi.(*ProtocolBFTCoSi).Dispatch+0x2b9	github.com/dedis/cothority/protocols/bftcosi/_test/_obj_test/bftcosi.go:192
1 @ 0x431afd 0x431bee 0x4064f7 0x4062d5 0x56c83f 0x4650e1
#	0x56c83e	github.com/dedis/cothority/sda.(*TreeNodeInstance).dispatchMsgReader+0x6de	/home/travis/gopath/src/github.com/dedis/cothority/sda/treenode.go:369
1 @ 0x431afd 0x442a03 0x4416ac 0x49ea01 0x49cef5 0x49ca23 0x48a35a 0x4650e1
#	0x49ea00	github.com/dedis/cothority/protocols/bftcosi.runProtocolOnceGo+0x1a50	/home/travis/gopath/src/github.com/dedis/cothority/protocols/bftcosi/bftcosi_test.go:227
#	0x49cef4	github.com/dedis/cothority/protocols/bftcosi.runProtocolOnce+0x74	/home/travis/gopath/src/github.com/dedis/cothority/protocols/bftcosi/bftcosi_test.go:186
#	0x49ca22	github.com/dedis/cothority/protocols/bftcosi.TestCheckRefuseMore+0x292	/home/travis/gopath/src/github.com/dedis/cothority/protocols/bftcosi/bftcosi_test.go:126
#	0x48a359	testing.tRunner+0xc9							/home/travis/.gimme/versions/go1.7.linux.amd64/src/testing/testing.go:610
1 @ 0x4650e1
1 @ 0x54138e 0x54112a 0x53c9ae 0x54ba83 0x49b818 0x401bd7 0x4316ed 0x4650e1
#	0x54138d	runtime/pprof.writeRuntimeProfile+0xbd				/home/travis/.gimme/versions/go1.7.linux.amd64/src/runtime/pprof/pprof.go:614
#	0x541129	runtime/pprof.writeGoroutine+0xc9				/home/travis/.gimme/versions/go1.7.linux.amd64/src/runtime/pprof/pprof.go:576
#	0x53c9ad	runtime/pprof.(*Profile).WriteTo+0x47d				/home/travis/.gimme/versions/go1.7.linux.amd64/src/runtime/pprof/pprof.go:298
#	0x54ba82	github.com/dedis/cothority/log.MainTest+0x312			/home/travis/gopath/src/github.com/dedis/cothority/log/lvl.go:395
#	0x49b817	github.com/dedis/cothority/protocols/bftcosi.TestMain+0x77	/home/travis/gopath/src/github.com/dedis/cothority/protocols/bftcosi/bftcosi_test.go:52
#	0x401bd6	main.main+0x316							github.com/dedis/cothority/protocols/bftcosi/_test/_testmain.go:110
#	0x4316ec	runtime.main+0x18c						/home/travis/.gimme/versions/go1.7.linux.amd64/src/runtime/proc.go:183
FAIL	github.com/dedis/cothority/protocols/bftcosi	180.013s
?   	github.com/dedis/cothority/protocols/byzcoin	[no test files]
?   	github.com/dedis/cothority/protocols/byzcoin/blockchain	[no test files]
?   	github.com/dedis/cothority/protocols/byzcoin/blockchain/blkparser	[no test files]
ok  	github.com/dedis/cothority/protocols/byzcoin/cosi	1.107s	coverage: 64.6% of statements
?   	github.com/dedis/cothority/protocols/byzcoin/ntree	[no test files]
?   	github.com/dedis/cothority/protocols/byzcoin/pbft	[no test files]
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
--- FAIL: TestCosi (2.06s)
	cosi_test.go:63: Could not get signature verification done in time
FAIL
coverage: 61.5% of statements
FAIL	github.com/dedis/cothority/protocols/cosi	2.075s
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
--- FAIL: TestCoSimul (2.26s)
	cosi_test.go:55: Could not get signature verification done in time
FAIL
coverage: 27.0% of statements
1 instances of:
github.com/dedis/cothority/network.(*LocalListener).Listen(0xc420123380, 0xc420146940, 0x10, 0x752780)
	/home/travis/gopath/src/github.com/dedis/cothority/network/local.go:397 +0x289
github.com/dedis/cothority/network.(*LocalHost).Listen(0xc420130f80, 0xc420146940, 0x180001, 0x0)
	<autogenerated>:65 +0x73
github.com/dedis/cothority/network.(*Router).Start(0xc42013c960)
	/home/travis/gopath/src/github.com/dedis/cothority/network/router.go:83 +0xe7
created by github.com/dedis/cothority/sda.(*LocalTest).NewLocalConode
	/home/travis/gopath/src/github.com/dedis/cothority/sda/local.go:389 +0x103
FAIL	github.com/dedis/cothority/protocols/cosimul	2.909s
?   	github.com/dedis/cothority/protocols/example	[no test files]
ok  	github.com/dedis/cothority/protocols/example/channels	1.050s	coverage: 43.1% of statements
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
Didn't finish in time
goroutine profile: total 7
2 @ 0x431acd 0x431bbe 0x4066c7 0x4064a5 0x53b199 0x5482a3 0x53c017 0x4649e1
#	0x53b198	github.com/dedis/cothority/network.(*LocalListener).Listen+0x288	/home/travis/gopath/src/github.com/dedis/cothority/network/local.go:397
#	0x5482a2	github.com/dedis/cothority/network.(*LocalHost).Listen+0x72		<autogenerated>:65
#	0x53c016	github.com/dedis/cothority/network.(*Router).Start+0xe6			/home/travis/gopath/src/github.com/dedis/cothority/network/router.go:83
1 @ 0x431acd 0x431bbe 0x4066c7 0x4064a5 0x48a26e 0x48eb5a 0x489c8a 0x48b64b 0x48a820 0x534659 0x4649e1
#	0x48a26d	testing.(*T).Run+0x56d					/home/travis/.gimme/versions/go1.7.linux.amd64/src/testing/testing.go:647
#	0x48eb59	testing.RunTests.func1+0xb9				/home/travis/.gimme/versions/go1.7.linux.amd64/src/testing/testing.go:793
#	0x489c89	testing.tRunner+0xc9					/home/travis/.gimme/versions/go1.7.linux.amd64/src/testing/testing.go:610
#	0x48b64a	testing.RunTests+0x4ba					/home/travis/.gimme/versions/go1.7.linux.amd64/src/testing/testing.go:799
#	0x48a81f	testing.(*M).Run+0x12f					/home/travis/.gimme/versions/go1.7.linux.amd64/src/testing/testing.go:743
#	0x534658	github.com/dedis/cothority/log.MainTest.func1+0x38	/home/travis/gopath/src/github.com/dedis/cothority/log/lvl.go:386
1 @ 0x431acd 0x431bbe 0x4066c7 0x4064a5 0x56ae9f 0x4649e1
#	0x56ae9e	github.com/dedis/cothority/sda.(*TreeNodeInstance).dispatchMsgReader+0x6de	/home/travis/gopath/src/github.com/dedis/cothority/sda/treenode.go:369
1 @ 0x431acd 0x4428f3 0x44159c 0x49b035 0x489c8a 0x4649e1
#	0x49b034	github.com/dedis/cothority/protocols/example/handlers_test.TestNode+0x994	/home/travis/gopath/src/github.com/dedis/cothority/protocols/example/handlers/example_test.go:31
#	0x489c89	testing.tRunner+0xc9								/home/travis/.gimme/versions/go1.7.linux.amd64/src/testing/testing.go:610
1 @ 0x4649e1
1 @ 0x52dd9e 0x52db3a 0x5293be 0x532c33 0x49a684 0x401cc7 0x4316bd 0x4649e1
#	0x52dd9d	runtime/pprof.writeRuntimeProfile+0xbd						/home/travis/.gimme/versions/go1.7.linux.amd64/src/runtime/pprof/pprof.go:614
#	0x52db39	runtime/pprof.writeGoroutine+0xc9						/home/travis/.gimme/versions/go1.7.linux.amd64/src/runtime/pprof/pprof.go:576
#	0x5293bd	runtime/pprof.(*Profile).WriteTo+0x47d						/home/travis/.gimme/versions/go1.7.linux.amd64/src/runtime/pprof/pprof.go:298
#	0x532c32	github.com/dedis/cothority/log.MainTest+0x312					/home/travis/gopath/src/github.com/dedis/cothority/log/lvl.go:395
#	0x49a683	github.com/dedis/cothority/protocols/example/handlers_test.TestMain+0x53	/home/travis/gopath/src/github.com/dedis/cothority/protocols/example/handlers/example_test.go:14
#	0x401cc6	main.main+0x316									github.com/dedis/cothority/protocols/example/handlers/_test/_testmain.go:106
#	0x4316bc	runtime.main+0x18c								/home/travis/.gimme/versions/go1.7.linux.amd64/src/runtime/proc.go:183
FAIL	github.com/dedis/cothority/protocols/example/handlers	180.013s
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: receive server identity failed: Received wrong type during negotiation sda.ProtocolMsgReceived wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsgreceive server identity failed:
 Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed:receive server identity failed:  Received wrong type during negotiation sda.ProtocolMsgReceived wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
Didn't finish in time
goroutine profile: total 136
100 @ 0x431c6d 0x431d5e 0x406667 0x406485 0x5ff80b 0x5ff25c 0x60283f 0x465311
#	0x5ff80a	github.com/dedis/cothority/network.(*connQueue).pop+0x8a	/home/travis/gopath/src/github.com/dedis/cothority/network/local.go:307
#	0x5ff25b	github.com/dedis/cothority/network.(*LocalConn).Receive+0x8b	/home/travis/gopath/src/github.com/dedis/cothority/network/local.go:233
#	0x60283e	github.com/dedis/cothority/network.(*Router).handleConn+0x30e	/home/travis/gopath/src/github.com/dedis/cothority/network/router.go:194
16 @ 0x431c6d 0x431d5e 0x406667 0x406445 0x564a3f 0x465311
#	0x564a3e	github.com/dedis/cothority/sda.(*TreeNodeInstance).dispatchMsgReader+0x6de	/home/travis/gopath/src/github.com/dedis/cothority/sda/treenode.go:369
16 @ 0x431c6d 0x431d5e 0x406667 0x406445 0x6001d9 0x60d2e3 0x601057 0x465311
#	0x6001d8	github.com/dedis/cothority/network.(*LocalListener).Listen+0x288	/home/travis/gopath/src/github.com/dedis/cothority/network/local.go:397
#	0x60d2e2	github.com/dedis/cothority/network.(*LocalHost).Listen+0x72		<autogenerated>:65
#	0x601056	github.com/dedis/cothority/network.(*Router).Start+0xe6			/home/travis/gopath/src/github.com/dedis/cothority/network/router.go:83
1 @ 0x431c6d 0x431d5e 0x406667 0x406445 0x48ab9e 0x48f48a 0x48a5ba 0x48bf7b 0x48b150 0x543399 0x465311
#	0x48ab9d	testing.(*T).Run+0x56d					/home/travis/.gimme/versions/go1.7.linux.amd64/src/testing/testing.go:647
#	0x48f489	testing.RunTests.func1+0xb9				/home/travis/.gimme/versions/go1.7.linux.amd64/src/testing/testing.go:793
#	0x48a5b9	testing.tRunner+0xc9					/home/travis/.gimme/versions/go1.7.linux.amd64/src/testing/testing.go:610
#	0x48bf7a	testing.RunTests+0x4ba					/home/travis/.gimme/versions/go1.7.linux.amd64/src/testing/testing.go:799
#	0x48b14f	testing.(*M).Run+0x12f					/home/travis/.gimme/versions/go1.7.linux.amd64/src/testing/testing.go:743
#	0x543398	github.com/dedis/cothority/log.MainTest.func1+0x38	/home/travis/gopath/src/github.com/dedis/cothority/log/lvl.go:386
1 @ 0x431c6d 0x431d5e 0x406667 0x406445 0x49600c 0x49c788 0x48a5ba 0x465311
#	0x49600b	github.com/dedis/cothority/protocols/jvss.(*JVSS).Start+0x6fb	github.com/dedis/cothority/protocols/jvss/_test/_obj_test/jvss.go:135
#	0x49c787	github.com/dedis/cothority/protocols/jvss.TestJVSS+0x687	/home/travis/gopath/src/github.com/dedis/cothority/protocols/jvss/jvss_test.go:45
#	0x48a5b9	testing.tRunner+0xc9						/home/travis/.gimme/versions/go1.7.linux.amd64/src/testing/testing.go:610
1 @ 0x465311
1 @ 0x53cd7e 0x53cb1a 0x53839e 0x541903 0x49bdc4 0x401c67 0x43185d 0x465311
#	0x53cd7d	runtime/pprof.writeRuntimeProfile+0xbd			/home/travis/.gimme/versions/go1.7.linux.amd64/src/runtime/pprof/pprof.go:614
#	0x53cb19	runtime/pprof.writeGoroutine+0xc9			/home/travis/.gimme/versions/go1.7.linux.amd64/src/runtime/pprof/pprof.go:576
#	0x53839d	runtime/pprof.(*Profile).WriteTo+0x47d			/home/travis/.gimme/versions/go1.7.linux.amd64/src/runtime/pprof/pprof.go:298
#	0x541902	github.com/dedis/cothority/log.MainTest+0x312		/home/travis/gopath/src/github.com/dedis/cothority/log/lvl.go:395
#	0x49bdc3	github.com/dedis/cothority/protocols/jvss.TestMain+0x53	/home/travis/gopath/src/github.com/dedis/cothority/protocols/jvss/jvss_test.go:12
#	0x401c66	main.main+0x316						github.com/dedis/cothority/protocols/jvss/_test/_testmain.go:104
#	0x43185c	runtime.main+0x18c					/home/travis/.gimme/versions/go1.7.linux.amd64/src/runtime/proc.go:183
FAIL	github.com/dedis/cothority/protocols/jvss	180.025s
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
Timeout of 1s reached. &{[112 114 111 112 97 103 97 116 101]} %!s(<nil>)
FAIL	github.com/dedis/cothority/protocols/manage	1.052s
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
receive server identity failed: Received wrong type during negotiation sda.ProtocolMsg
--- FAIL: TestNtree (2.05s)
	ntree_test.go:54: Protocol didn't finish in time
FAIL
</code></pre>
</details>

**Comment by nikkolasg** [comment]
At least 26 times Travis was happy.

File: network/local.go [hunk 6]
```diff
@@ -277,27 +277,47 @@ func (lc *LocalConn) Type() ConnType {
 // All operations are thread-safe.
 // The messages are marshalled and stored in the queue as a slice of bytes.
 type connQueue struct {
-	*sync.Cond
-	queue  [][]byte
-	closed bool
+	incomingQueue chan []byte
+	outgoingQueue chan []byte
+	closeCh       chan bool
+	wg            sync.WaitGroup
```
Comment (Liamsi) [inline network/local.go]: The usage of this waiting group is a little confusing: There is never a "group of events" or a "collection of goroutines to finish" or to wait on; instead it is always just one event to wait for (closing). In other words: the group gets incremented exactly *once*, [here](https://github.com/dedis/cothority/pull/673/files#diff-758a279d81fc93cf992b979af141f431R296). To me it seems a channel would be the right tool to signal: "hey we are done here". https://golang.org/pkg/sync/#WaitGroup

This said, **I still approve of this pull** as it fixes many other issues (also this little detail is buried in unexported methods).

File: network/client_test.go [hunk 7]
```diff
@@ -24,6 +24,9 @@ func testClient(t *testing.T, fac routerFactory, cl clientFactory) {
 		t.Fatal(err)
 	}
 	go r.Start()
+	for !r.Listening() {
+		time.Sleep(20 * time.Millisecond)
+	}
```
Comment (Liamsi) [inline network/client_test.go]: Could this lead to an endless loop? Does it timeout if (for whatever reasons) we could never start listening?

File: network/local.go [hunk 8]
```diff
@@ -277,27 +277,47 @@ func (lc *LocalConn) Type() ConnType {
...
+			close(c.incomingQueue)
+			return
+		}
 	}
 }
 
 // push inserts a packet in the queue.
-// push won't work if the connQueue is already closed and silently return.
+// push should not be called if the connQueue is closed. Since it's the
+// LocalManager's reponsability, it is enforced.
```
Comment (Liamsi) [inline network/local.go]: typo: reponsability->responsibility

File: network/local.go [hunk 9]
```diff
@@ -277,27 +277,47 @@ func (lc *LocalConn) Type() ConnType {
...
 func (c *connQueue) push(buff []byte) {
-	c.L.Lock()
-	defer c.L.Unlock()
-	if c.closed {
-		return
-	}
-	c.queue = append(c.queue, buff)
-	c.Signal()
+	c.incomingQueue <- buff
```
Comment (Liamsi) [inline network/local.go]: Nitpicky question: If push is only *one* line and only used exactly once: Wouldn't it be better to remove this method including its comments? I guess, the push/pop semantic is the only reason why this exists?

File: network/client_test.go (hunk 7 above)
Comment (nikkolasg) [inline network/client_test.go]: Yes, it could if something is wrong, and if so, it's a problem we should solve, so I'm happy that it's in the test ;) 
This line was added just to make sure the test was not failing because of the listener not really listening yet, but in fact it was not that. Still it's a good habit to make sure the listener is really listening before going on with our test. That's the same code which is in `sda.LocalTest` which is already merged...

Comment (Liamsi) [inline network/client_test.go]: I missed that these lines are in a test only. Totally makes sense.

File: network/local.go (hunk 9 above)
Comment (nikkolasg) [inline network/local.go]: I agree with you. And to push the idea further, we could even remove the `connQueue` struct entirely now that it is only comprised of channels and put *all* the functionality in the `LocalConn` struct.
 However, do we want to do this now / here ? I mean this is only to fix bugs, not to re-design again and again. I'm happy to do it later in a future PR if we make an issue for it. Because removing `connQueue` will also lead to a whole new serie of tests, scrutinization, etc and this PR will be merged in one month...

File: network/local.go (hunk 6 above)
Comment (nikkolasg) [inline network/local.go]: I'll try and see if it works and is not ugly. Because if it's the word Collection that bothers you, think of this routine of a collection of size 1. The syntax of sync.WaitGroup is much clearer `Add(), Done(), Wait()` and it's really for:
> A WaitGroup waits for a collection of goroutines to finish

I want my listening go routine to finish.

Comment (nikkolasg) [inline network/local.go]: Ok it's still light, so let's go for it :)

**Comment by nikkolasg** [comment]
22 times ran with the latests changes.

File: network/local.go (hunk 9 above)
Comment (ineiti) [inline network/local.go]: I think we need to include _some_ cleanup (very objective measurement) whenever we can. Because we already have tons of __to be done later__ issues. Perhaps not here, but at least for me some continous refactoring is always good. In some measure, of course. But here you can perhaps open an issue.

Comment (nikkolasg) [inline network/local.go]: and done it is. let's see our dear friend travis's reaction.

**Comment by nikkolasg** [comment]
32 times travis was happy (I gave the poor guy a rest)

File: network/router.go [hunk 10]
```diff
@@ -194,7 +199,7 @@ func (r *Router) handleConn(remote *ServerIdentity, c Conn) {
 
 			if err == ErrClosed || err == ErrEOF {
 				// Connection got closed.
-				log.Lvl3(r.address, "handleConn with closed connection: stop (dst=", remote.Address, ")")
+				log.LLvl3(r.address, "handleConn with closed connection: stop (dst=", remote.Address, ")")
```
Comment (ineiti) [inline network/router.go]: `log.Lvl3`

File: network/router_test.go [hunk 11]
```diff
@@ -117,14 +117,17 @@ func testRouterAutoConnection(t *testing.T, fac routerFactory) {
...
+
 	if err := h2.Stop(); err != nil {
 		t.Fatal("Should be able to stop h2")
 	}
-	h2.connsMut.Lock()
-	delete(h2.connections, h1.ServerIdentity.ID)
-	h2.connsMut.Unlock()
 	err = h1.Send(h2.ServerIdentity, &SimpleMessage{12})
 	require.NotNil(t, err)
+
```
Comment (ineiti) [inline network/router_test.go]: Linus-linter: no empty line before end of method...

File: network/router_test.go [hunk 12]
```diff
@@ -172,47 +175,64 @@ func TestRouterMessaging(t *testing.T) {
...
-		p.t.Fatal("Too many response ??")
 	}
-	msg := pack.Msg.(SimpleMessage)
-	p.r.Send(pack.ServerIdentity, &msg)
+
+	p.firstRound[remote] = true
+	if err := p.r.Send(pack.ServerIdentity, &SimpleMessage{3}); err != nil {
+		p.t.Fatal("Could not send to first round dest.")
+	}
+
```
Comment (ineiti) [inline network/router_test.go]: LL: no empty line before end of method.

File: network/router.go [hunk 13]
```diff
@@ -162,9 +163,13 @@ func (r *Router) connect(si *ServerIdentity) (Conn, error) {
...
-	r.registerConnection(si, c)
+	if err := r.registerConnection(si, c); err != nil {
+		return nil, err
+	}
 
-	r.launchHandleRoutine(si, c)
+	if err := r.launchHandleRoutine(si, c); err != nil {
+		return nil, err
+	}
 	return c, nil
```
Comment (ineiti) [inline network/router.go]: Linus linter: no newline before end of method.

**Comment by nikkolasg** [comment]
@ineiti done your comments

File: network/router.go (hunk 10 above)
Comment (ineiti) [inline network/router.go]: I just looked at github...
