### PR TITLE
Fix documentation to say that LatestID may be updated

### LINKED ISSUE #1110: StoreSkipBlock potentially overwrites prev when it is supplied by the Client
From reading the code, `prev` is overwritten on this line https://github.com/dedis/cothority/blob/4844826d4b0fc2b8402bcaa36a980e6f76b45ac9/skipchain/skipchain.go#L263 even when it is supplied by the client https://github.com/dedis/cothority/blob/4844826d4b0fc2b8402bcaa36a980e6f76b45ac9/skipchain/skipchain.go#L215

Unless I missed something, I think this is not the right behaviour. 

If the client knows the latest block and wants to add the new block after it, we should respect its wish.

### PR DESCRIPTION
**Pull request by kc1212**
I give my reasons for why fixing the documentation may be a better idea in this issue https://github.com/dedis/cothority/issues/1110

Closes #1110

### CODE REVIEW

**Comment by kc1212** [comment]
New version available: changed `LatestID` to `TargetSkipChainID`. The client is encouraged to supply the `TargetSkipChainID`, but for backward compatibility reasons, it can also be used as a skipblock ID.

File: skipchain/api.go [hunk 1]
```diff
@@ -25,24 +25,27 @@ func NewClient() *Client {
 	return &Client{Client: onet.NewClient(cothority.Suite, "Skipchain")}
 }
 
-// StoreSkipBlockSignature asks the cothority to store the new skipblock, and eventually
-// attach it to the 'latest' skipblock.
-//  - latest is the skipblock where the new skipblock is appended. If ro and d
-//   are nil, a new skipchain will be created with 'latest' as genesis-block.
+// StoreSkipBlockSignature asks the cothority to store the new skipblock, and
+// eventually attach it to after the target skipblock.
```
Comment (jeffallen) [inline skipchain/api.go]: s/it to after/it after/         I think that's easier to read, no?

**Comment by jeffallen** [comment]
I agree with this, but I'm leaving it to Linus to merge it since I'm only halfway here these days.
