### PR TITLE
Tentative to stabilize Jenkins

### LINKED ISSUE #1974: Spurious Travis failure
Here is a spurious failure on travis:

```
2 19/24/06 13:25:32.469739374: ( byzcoin.(*defaultTxProcessor).CollectTx: 160) - local://127.0.0.1:2030 timeout while collecting transactions from other nodes
2 19/24/06 13:25:32.992295242: ( byzcoin.(*defaultTxProcessor).CollectTx: 160) - local://127.0.0.1:2030 timeout while collecting transactions from other nodes
E 19/24/06 13:25:33.262757461: (                  v3.wsHandler.ServeHTTP: 236) - Got an error while executing ByzCoin/AddTxRequest: transaction didn't get included after 10s (2 * t_block * 10)
2 19/24/06 13:25:33.263211887: (            v3.wsHandler.ServeHTTP.func1: 163) - ws close 127.0.0.1:35504 n 1 rx 3288 tx 0
--- FAIL: TestService_SetConfigRosterReplace (19.14s)
    require.go:765: 
        	Error Trace:	service_test.go:1656
        	Error:      	Expected nil, but got: &websocket.CloseError{Code:4000, Text:"transaction didn't get included after 10s (2 * t_block * 10)"}
        	Test:       	TestService_SetConfigRosterReplace
FAIL
```

### PR DESCRIPTION
**Pull request by Gilthoniel**
This adds different fixes for the test failing on Jenkins. It prevents the leader to create with too many transactions when a block takes time to be created. It also improves the signer counts request from a client. See my job on Jenkins.

Related to dedis/protobuf#68
Fixes #1974 #2024 

---

🙅‍ Friendly checklist:

- [x] 0. Code comments are added (or updated) when/where needed and explain the WHY of the code.
- [x] 1. Design choices, user documentation and any additional doc are added (or updated) in READMEs.
- [x] 2. Any new behavior is tested and small units of code that can be are unit tested.
- [x] 3. Code comments are added on tests to explain what they do.
- [x] 4. Errors are systematically wrapped, following the `[failed to | counldn't do] ACTION THAT FAILED: " + err.Error()` format.
- [x] 5. Hard limit of 80 chars is always respected.
- [x] 6. Changes are backward compatible.
- [x] 7. Indentation level does not exceed 5, althought 4 is already suspicious.
- [x] 8. Functions, files, and packages are kept to a manageable size and decomposed into smaller units if needed.
- [x] 9. There are no magic values.

### CODE REVIEW

File: byzcoin/tx_pipeline.go [hunk 1]
```diff
@@ -483,12 +460,41 @@ func (p *txPipeline) processTxs(initialState *txProcessorState) {
...
+				// when processing, we take the latest state
+				// (the last one) and then apply the new transaction to it
+				newStates, err := p.processor.ProcessTx(tx, currentState[len(currentState)-1])
 				if err != nil {
-					log.Error("reverting to last known state because proposal refused:", err)
-					currentState = []*txProcessorState{p.processor.GetLatestGoodState()}
+					log.Error("processing transaction failed with error: " + err.Error())
+				} else {
+					// remove the last one from currentState because
+					// it might be getting updated and the append newStates
```
Comment (nkcr) [inline byzcoin/tx_pipeline.go]: ? (I know it's a legacy comment)
>  and the append newStates

File: byzcoin/tx_pipeline.go [hunk 2]
```diff
@@ -483,12 +460,41 @@ func (p *txPipeline) processTxs(initialState *txProcessorState) {
 						}
```
Comment (nkcr) [inline byzcoin/tx_pipeline.go]: While we're at it we could refactor this go routine to:

```
func(state *txProcessorState) {
	p.wg.Add(1)
	defer p.wg.Done()
	if state != nil {
		// NOTE: ProposeBlock might block for a long time,
		// but there's nothing we can do about it at the moment
		// other than waiting for the timeout.
		err := p.processor.ProposeBlock(state)
		if err != nil {
			log.Error("failed to propose block:", err)
			proposalResult <- err
			return
		}
	}
	proposalResult <- nil
}(inState)
```

(I can do it in another PR if you want)

File: byzcoin/api.go [hunk 3]
```diff
@@ -441,6 +441,30 @@ func (c *Client) StreamTransactions(handler func(StreamingResponse, error)) erro
...
+	if !ok {
+		return errors.New("wrong type of response")
+	}
+
+	// This assumes the client is up-to-date with the latest block which
+	// is usually right as it is updated after each GetProof. The goal is
+	// to insure that we got the data from the latest block.
+	// Note: index 0 is checked for backwards compatibility.
+	if reply.Index != 0 && c.Latest != nil {
+		if uint64(c.Latest.Index) > reply.Index {
```
[the remark this answers is not in the document]
Comment (nkcr) [reply byzcoin/api.go]: Nothing to change here, just wondering

[the remark this answers is not in the document]
Comment (Gilthoniel) [reply byzcoin/api.go]: It's actually possible for `reply.Index` to be higher than the currently know latest block index by the client as blocks might have been created since the last GetProof or similar.

If that happens, it should accept the counter because the client should not add transaction since.

File: byzcoin/tx_pipeline.go (hunk 1 above)
Comment (Gilthoniel) [reply byzcoin/tx_pipeline.go]: the = then
