### PR TITLE
Check 724

### LINKED ISSUE #724: (cosi|cothorityd) check improvements
when running `check` and a conode fails, 
now: it is still tested as a pair against the other conodes
wanted: is not tested anymore

now: `cothorityd check -g group.toml`
after: `cothorityd check group.toml`

now: `check` verifies all pairs per default
after: `check` verifies individual servers and once the group in total, but adds a `--detail`-flag to do the pairwise-test

### PR DESCRIPTION
**Pull request by ineiti**
closes #724

### CODE REVIEW

File: cothority.go [hunk 1]
```diff
@@ -80,15 +80,20 @@ func main() {
...
+			ArgsUsage: "Cothority group definition file",
+			Action:    checkConfig,
 			Flags: []cli.Flag{
 				cli.StringFlag{
 					Name:  "g",
 					Usage: "Cothority group definition file",
 				},
+				cli.BoolFlag{
+					Name:  "detail,l",
+					Usage: "Show detail in signing",
```
Comment (nikkolasg) [inline cothority.go]: More detail for detail ^^  Namely, it will try pair wise servers together or stg like that.

File: cothority.go [hunk 2]
```diff
@@ -115,5 +120,8 @@ func runServer(ctx *cli.Context) {
 // signature from each.
 func checkConfig(c *cli.Context) error {
 	tomlFileName := c.String("g")
-	return check.Config(tomlFileName)
+	if c.NArg() > 0 {
+		tomlFileName = c.Args().First()
+	}
+	return check.Config(tomlFileName, c.Bool("detail"))
```
Comment (nikkolasg) [inline cothority.go]: so the verification process is not in any lib or so ? It's "included" in the cosi, and the cothority depends on it ? mmhhh... We might want to do something else for later.

Comment (ineiti) [inline cothority.go]: yes, it's part of cosi, as it's signing. So it _is_ in a library, but the library is in the cosi-directory.
