### PR TITLE
Testing and simplifying catchup

### LINKED ISSUE #1980: syncChain can go into an infinite loop
Ineiti writes: This happened when I deleted the `.db` on `gasser.blue` and then tried to get the chain loaded from the roster again.

Proposed changes:
- [x] verify why it passes the test, and get the test to fail, then fix it
- [x] work on a better way to have a node update / download a given chain

### PR DESCRIPTION
**Pull request by ineiti**
The previous tests only unit-tested the catchup and downloadDB methods. This test
runs it in a more production-like environment with transactions being processed
as the node catches up. A couple of problems got fixed:

- downloadDB now stores the new blocks
- byzcoin.verifySkipblock checks if it needs to catchup

Depends on dedis/onet#559
Closes #1980

### CODE REVIEW

File: byzcoin/collect_tx.go [hunk 1]
```diff
@@ -112,6 +112,12 @@ func (p *CollectTxProtocol) Start() error {
 
 // Dispatch runs the protocol.
 func (p *CollectTxProtocol) Dispatch() error {
+	defer func() {
+		if r := recover(); r != nil {
+			log.Print(r)
+			log.Print(log.Stack())
```
Comment (kc1212) [inline byzcoin/collect_tx.go]: use `log.Error`
also: under what condition does `Dispatch` panic? is it not possible to fix the panic?

File: byzcoin/service.go [hunk 2]
```diff
@@ -1001,106 +1001,115 @@ func (s *Service) downloadDB(sb *skipchain.SkipBlock) error {
...
-					return nil
-				})
-				if err != nil {
-					return fmt.Errorf("Couldn't store entries: %s", err.Error())
-				}
-				if len(resp.KeyValues) < catchupFetchDBEntries {
-					break
-				}
+		// Create a roster with all nodes other than us
+		// TODO: remove this and use the future parallel client
```
Comment (kc1212) [inline byzcoin/service.go]: are you using the parallel client? the PR says it depends on it but I don't see where the parallel client is used

Comment (ineiti) [reply byzcoin/service.go]: This is in #2001

File: byzcoin/collect_tx.go (hunk 1 above)
Comment (ineiti) [reply byzcoin/collect_tx.go]: Oups - debugging stuff. There was an error coming from `dedis/protobuf`, where the defer/recover in there tried to cast a value to an `error`, but it failed to do so. Unfortunately I cannot reproduce it anymore...

File: byzcoin/service.go (hunk 2 above)
Comment (ineiti) [reply byzcoin/service.go]: The adding of `SendProtobufParallel` was much bigger than thought, as I had to adjust a couple of tests to the new parallelized calls. Now I don't have any `SendProtobufParallel` in it anymore, so I removed it from the description...

File: byzcoin/service.go [hunk 3]
```diff
@@ -1001,106 +1001,115 @@ func (s *Service) downloadDB(sb *skipchain.SkipBlock) error {
...
+		s.stateTries[idStr] = st
+		s.stateTriesLock.Unlock()
+		chain, err := skCl.GetUpdateChain(newRoster, sb.SkipChainID())
+		if err != nil {
+			return err
 		}
-		log.Errorf("Couldn't load database from %s - got error %s", roster.List[0], err)
+		for _, sb := range chain.Update {
+			log.Lvlf2("Storing block %d: %x", sb.Index, sb.CalculateHash())
+			s.db().Store(sb)
```
Comment (kc1212) [inline byzcoin/service.go]: when you're storing the skipblock, can you also check that you're only storing the skipblocks that are at the same index or below the stateTrie? otherwise the blocks and the trie might become out of sync

Comment (ineiti) [reply byzcoin/service.go]: for every block that is stored in the db, `updateTrieCallback` will be called. If the block is newer than the trie, which might happen if another block gets created while the db is downloaded, `updateTrieCallback` will make sure that the block will be added to the trie:

- If it's just one new block, all is well, as this is the normal path in `updateTrieCallback`
- if it's two new blocks, the go-routine with `s.catchUp` in it will be called, and all is well
- if it's three or more new blocks, multiple go-routines will be called, each with a `s.catchUp` call. The first `s.catchUp` will update to the latest block, and all further `s.catchUp` will pass through as there is nothing to update to

And no, I didn't think this through while writing the code ;)
