### PR TITLE
better blocking on new requests

### LINKED ISSUE #913: Need blocking of skipblocks during BFTCosi
When two clients ask to add a new block in parallel, skipblock will fail:

Given 3 nodes (node0..node2) and a block A
t0: Client1 asks node0 to add a block B to A
t0: Client2 asks simultaneously node5 to add a block C to A
t1: node0 asks nodes1..2 to check validity of block B
t1: node2 asks nodes0..1 to check validity of block C and create collective signature
t2: nodes0..2 approve block B and create collective signature, sending it to node0
t2: nodes0..2 approve block C and create collective signature, sending it to node2
t3: node0 propagates block A, B through system
t3: node2 propagates block A, C through system
t4: node1 wants to add block D to block A, but this will fail, because this block will not be approved, due to the presence of B or C.

At t2 we created a fork in our beloved skipchain, because we collectively signed two different future blocks :( 
My first idea is to use a `signatureinprogress`-list of blocks that are about to be signed, and then look up this list in the BFT-verification function. But this list is quite brittle, as we have to take care to remove failed signature attempts from it.

### PR DESCRIPTION
**Pull request by ineiti**
Closes #913

### CODE REVIEW

File: skipchain/skipchain.go [hunk 1]
```diff
@@ -623,6 +634,27 @@ func (s *Service) startPropagation(blocks []*SkipBlock) error {
...
+	return true
+}
+
+func (s *Service) newBlockEnd(sb *SkipBlock) bool {
+	s.newBlocksLock.Lock()
+	defer s.newBlocksLock.Unlock()
+	if _, processing := s.newBlocks[string(sb.Hash)]; !processing {
+		return false
+	}
+	network.Suite.Scalar().Zero()
```
Comment (nikkolasg) [inline skipchain/skipchain.go]: I guess that can be removed

File: skipchain/api.go [hunk 2]
```diff
@@ -23,6 +23,9 @@ const (
 	ErrorVerification
 	// ErrorOnet indicates an error from the onet framework
 	ErrorOnet
+	// ErrorBlockInProgress indicates that currently a block is being formed
+	// and propagated
+	ErrorBlockInProgress
```
Comment (nikkolasg) [inline skipchain/api.go]: Also indicates somewhere that change of protocol that only the leader can initiate requests for a new block to be signed, that's why this error exists in the first place too no ?

File: skipchain/skipchain.go (hunk 1 above)
Comment (ineiti) [inline skipchain/skipchain.go]: Oups - abused IntelliJ to look up the krypto-library ;)

File: skipchain/api.go (hunk 2 above)
Comment (ineiti) [inline skipchain/api.go]: Not only that, but also if a block is begin formed and you want to add a block at the same index as the one being formed.

File: skipchain/skipchain.go [hunk 3]
```diff
@@ -107,6 +112,15 @@ func (s *Service) StoreSkipBlock(psbd *StoreSkipBlock) (*StoreSkipBlockReply, on
...
 		}
+		if len(prev.ForwardLink) > 0 {
+			return nil, onet.NewClientErrorCode(ErrorBlockContent,
+				"the latest block already has a follower")
+		}
+		if !s.newBlockStart(prev) {
+			return nil, onet.NewClientErrorCode(ErrorBlockInProgress,
+				"this skipchain-id is currently processing a block")
+		}
+		defer s.newBlockEnd(prev)
```
Comment (nikkolasg) [inline skipchain/skipchain.go]: Just to make sure: where is the check that there's no fork on the skipchain (i.e. same parent block for two distinct blocks), and is that check called after this defer ?

Comment (ineiti) [inline skipchain/skipchain.go]: It's line 119 - it checks that the leader is not adding another block to the `prev`, which is the latest ackknowledged block.

File: skipchain/skipchain.go [hunk 4]
```diff
@@ -68,6 +69,10 @@ type Service struct {
 // added.
 func (s *Service) StoreSkipBlock(psbd *StoreSkipBlock) (*StoreSkipBlockReply, onet.ClientError) {
 	prop := psbd.NewBlock
+	if !s.ServerIdentity().Equal(prop.Roster.Get(0)) {
```
Comment (nikkolasg) [inline skipchain/skipchain.go]: Mhhh. Is this not hazardous ? 
Since the `prop.Roster.Get(0)` is coming from the client, the client could basically make anyone propose a block if he can re-arrange the Roster the way he wants, and it will still pass, as it's still the same roster ID or stg ?

Comment (ineiti) [inline skipchain/skipchain.go]: as far as I can see, this is not a problem. Changing the roster means a `view-change`. So as long as the verification-functions allow this view-change, that's OK.

Comment (nikkolasg) [inline skipchain/skipchain.go]: Does the verification function checks the ordering of the indivudual keys in the roster of a block ?

Comment (ineiti) [inline skipchain/skipchain.go]: In fact every new block can have a completely different `Roster`, so the problem is far worse ;)
This will only be better in skipchain.v2 where there will be a unified way of handling the roster. So if there are no other comments, I think this is ready to merge.
